import os

MONGO_HOST = os.environ['MONGO_HOST']
MONGO_PORT = os.environ['MONGO_PORT']
MONGO_USER = os.environ['MONGO_USER']
MONGO_PWD = os.environ['MONGO_PWD']
MONGO_DB_NAME = os.environ['MONGO_DB_NAME']
POSTGRES_DB_HOST = os.environ['POSTGRES_DB_HOST']
POSTGRES_DB_PORT = os.environ['POSTGRES_DB_PORT']
POSTGRES_DB_USER = os.environ['POSTGRES_DB_USER']
POSTGRES_DB_PASSWORD = os.environ['POSTGRES_DB_PASSWORD']
POSTGRES_DB_NAME = os.environ['POSTGRES_DB_NAME']

